/*
 * Copyright (c) 2024 Domatar
 */

package com.domatar.crypto;

import com.domatar.util.Base64Encoder;

import java.io.File;
import java.io.IOException;
import java.io.PrintWriter;
import java.nio.charset.StandardCharsets;

/**
 * One-time generator for the fixed dev keyset file used by
 * {@link SecurityMigration} on development / CI databases.
 *
 * <p>Run once, commit the output.  The file is deterministic for a given
 * JVM / SecureRandom implementation; if you need to regenerate it (e.g.
 * after a JDK upgrade changes the CSPRNG) you must also reseed both dev
 * databases with the new dump-*.sql files produced by the seed-rewrite step.
 *
 * <p>Output file ({@code mySQL/dev-keys/dev-keyset.txt}) format — one line per
 * seeded account, tab-separated:
 * <pre>
 *   usrId TAB oldActId TAB newActId TAB rootPubKeyB64 TAB rootPrvKeyB64
 * </pre>
 * Lines beginning with {@code #} are comments; blank lines are ignored.
 *
 * <p>Usage (from the project root after a full build):
 * <pre>
 *   java -cp &lt;classpath&gt; com.domatar.crypto.DevKeysetGen
 * </pre>
 * Or run via Maven exec:
 * <pre>
 *   mvn -pl domatar-core exec:java -Dexec.mainClass=com.domatar.crypto.DevKeysetGen
 * </pre>
 *
 * Spec-Security.txt PART 3.3; Update-Security.txt Task 2.13.
 */
public class DevKeysetGen
{
    /**
     * Tab-separated columns: usrId, oldActId, newActId, rootPubKeyB64, rootPrvKeyB64.
     * The order here defines the order in the output file.
     *
     * Format: { usrId, oldActId }  (newActId and key bytes are generated)
     */
    private static final String[][] ACCOUNTS = {
        // prv1 provider
        { "prv1@prv1",             "prv1@prv1"              },
        // prv2 provider
        { "prv2@prv2",             "prv2@prv2"              },
        // central host accounts
        { "quippin@quippin",       "quippin@quippin"        },
        { "appstore@appstore",     "appstore@appstore"      },
        { "bookstore@bookstore",   "bookstore@bookstore"    },
        { "spreadsheet@spreadsheet","spreadsheet@spreadsheet"},
        { "money@money",           "money@money"            },
        // prv1 human users
        { "davidb@quippin",        "david@quippin"          },
        { "bethb@quippin",         "beth@quippin"           },
        { "burtb@quippin",         "burt@quippin"           },
        { "marianneb@quippin",     "marianne@quippin"       },
        // prv2 human users
        { "hayay@avatarvia",       "haya@avatarvia"         },
        { "michab@avatarvia",      "micha@avatarvia"        },
        { "elenas@avatarvia",      "elana@avatarvia"        },
        { "shoshanb@avatarvia",    "shoshan@avatarvia"      },
    };

    /** Default output path, relative to the project root. */
    private static final String DEFAULT_OUTPUT = "mySQL/dev-keys/dev-keyset.txt";

    public static void main(final String[] args) throws IOException
    {
        final String outputPath = (args.length > 0) ? args[0] : DEFAULT_OUTPUT;

        final File outFile = new File(outputPath);
        outFile.getParentFile().mkdirs();

        try (final PrintWriter pw = new PrintWriter(outFile, StandardCharsets.UTF_8))
        {
            pw.println("# Domatar dev keyset — generated by DevKeysetGen.");
            pw.println("# Format: usrId<TAB>oldActId<TAB>newActId<TAB>rootPubKeyB64<TAB>rootPrvKeyB64");
            pw.println("# DO NOT use in production. Commit once; regenerate only when seeds change.");
            pw.println("#");

            for (final String[] row : ACCOUNTS)
            {
                final String usrId    = row[0];
                final String oldActId = row[1];

                final AccountKeys keys = AccountKeys.generate();

                final String newActId     = keys.actId;
                final String pubKeyB64    = Base64Encoder.encode(keys.rootPubKey);
                final String privKeyB64   = Base64Encoder.encode(keys.rootPrivKey);

                pw.printf("%s\t%s\t%s\t%s\t%s%n",
                    usrId, oldActId, newActId, pubKeyB64, privKeyB64);
            }
        }

        System.out.println("Wrote " + ACCOUNTS.length + " accounts to " + outputPath);
    }
}
